//>>built
define("xide/views/ACEEditor","dojo/_base/declare dojo/_base/lang dojo/has dojo/dom-class xide/layout/ContentPane xide/views/_EditorBase xide/views/TextEditor xide/utils xide/types xide/factory xide/widgets/ActionSelectWidget dijit/MenuItem dojo/cookie xide/bean/Action".split(" "),function(u,v,l,h,w,x,y,m,d,n,z,k,p,g){var q={},r={},t="abap actionscript ada apache_conf applescript asciidoc assembly_x86 autohotkey batchfile c_cpp cirru clojure cobol coffee coldfusion csharp css curly d dart diff django dockerfile dot ejs erlang forth ftl gherkin gitignore glsl golang groovy haml handlebars haskell haxe html html_ruby ini jack jade java javascript json jsoniq jsp jsx julia latex less liquid lisp livescript logiql lsl lua luapage lucene matlab makefile markdown mel mushcode mysql nix objectivec ocaml pascal perl pgsql php plain_text powershell prolog protobuf python r rdoc rhtml ruby rust sass scad scala scheme scss sh sjs smarty snippets soy_template space sql stylus svg tcl tex text textile toml typescript twig vala vbscript velocity verilog vhdl xml xquery yaml".split(" ");
return u("xide/views/ACEEditor",[w,x],{closeable:!0,aceEditor:null,value:null,editorOptions:null,fileName:null,didStart:!1,defaultTheme:"idle_fingers",autoSelect:!0,autoFocus:!0,iconClassNormal:null,lastSavedContent:null,cookiePrefix:"",onShow:function(){this.inherited(arguments);this.autoFocus&&this.aceEditor&&this.focus()},getActiveItem:function(){return null},hasItemActions:function(){return!0},getItem:function(){return{}},getEditor:function(){return this.aceEditor||this},getItemActions:function(){var a=
[],c=this,b=g.create("Reload","el-icon-refresh","File/Reload",!0,null,d.ITEM_TYPE.TEXT,"fileAction",null,!0,function(){c.reload()}).setVisibility(d.ACTION_VISIBILITY.ACTION_TOOLBAR,{label:""}),A=g.create("Save","fa-floppy-o","File/Save",!0,null,d.ITEM_TYPE.TEXT,"fileAction",null,!0,function(){c.save()},{accelKey:"CTRL+S"}).setVisibility(d.ACTION_VISIBILITY.ACTION_TOOLBAR,{label:""}),f=g.create("Increase Font Size","fa-search-plus","View/Increase Font Size",!0,null,d.ITEM_TYPE.TEXT,"editorAction",
null,!0,function(){var a=c.aceEditor.getEditor(),b=parseInt(a.getFontSize(),10)||12;a.setFontSize(b+1)},{accelKey:"CTRL+"}).setVisibility(d.ACTION_VISIBILITY.ACTION_TOOLBAR,{label:""}),e=g.create("Decrease Font Size","fa-search-minus","View/Decrease Font Size",!0,null,d.ITEM_TYPE.TEXT,"editorAction",null,!0,function(){var a=c.aceEditor.getEditor(),b=parseInt(a.getFontSize(),10)||12;a.setFontSize(Math.max(b-1||1))},{accelKey:"CTRL-"}).setVisibility(d.ACTION_VISIBILITY.ACTION_TOOLBAR,{label:""});a.push(b);
a.push(A);a.push(f);a.push(e);b=g.createDefault("Themes","fa-paint-brush","View/Themes","_a",null,{dummy:!0}).setVisibility(d.ACTION_VISIBILITY.ACTION_TOOLBAR,{label:""}).setVisibility(d.ACTION_VISIBILITY.MAIN_MENU,{show:!1}).setVisibility(d.ACTION_VISIBILITY.CONTEXT_MENU,null);a.push(b);this._addThemes(a);b=m.addWidget(z,{item:null,delegate:this,style:"float:left;",iconClass:"fa-code"},this,dojo.doc.createElement("div"),!0);this._addModes(b);b=g.createDefault("Syntax","fa-code","View/Syntax","_a",
null,{dummy:!0}).setVisibility(d.ACTION_VISIBILITY.ACTION_TOOLBAR,{label:"",_widget:b}).setVisibility(d.ACTION_VISIBILITY.MAIN_MENU,{show:!1}).setVisibility(d.ACTION_VISIBILITY.CONTEXT_MENU,null);a.push(b);return a},reload:function(a){var c=this;a&&(this.dataItem=a);this.getContent(function(a){c.setValue(a)},this.dataItem)},save:function(){this.saveContent()},_createModeWidget:function(a,c){var b=this,d=new k({label:a,checked:!1,mode:c,iconClass:"fa-code"});dojo.connect(d,"onClick",function(){b.setMode(c)});
return d},onContentChange:function(a){null!=this.controlButton&&h.toggle(this.controlButton.domNode,"unsavedContent",a)},attachACE:function(a){var c=this._getMode(this.fileName),b=this;a={region:"center",value:a,style:"margin: 0; padding: 0; position:relative;overflow: auto;height:inherit;width:inherit;text-align:left;",readOnly:!1,tabSize:2,softTabs:!1,wordWrap:!1,showPrintMargin:!1,highlightActiveLine:!1,fontSize:"14px",showGutter:!0,className2:"editor-ace ace_editor",className:"editor-ace ace_editor",
onDidChange:function(){b.onContentChange(b.getValue()!==b.lastSavedContent)}};this.editorOptions&&(a=v.mixin(a,this.editorOptions));a=new y(a,dojo.doc.createElement("div"));this.containerNode.appendChild(a.domNode);a.startup();this.aceEditor=a;this.aceEditor.setOptions();if(a=p(this.cookiePrefix+"_ace"))this.defaultTheme=a;setTimeout(function(){b.setMode(c);b.setTheme(b.defaultTheme);n.publish(d.EVENTS.RESIZE,{},this);b.autoSelect&&n.publish(d.EVENTS.ITEM_SELECTED,{owner:b,item:b.item},b)},10)},loadScript:function(a,
c,b){c=document.createElement("script");c.type="application/javascript";c.src=a;c.onload=function(){b&&b()};document.body.appendChild(c)},getThemeData:function(){return[["Chrome"],["Clouds"],["Crimson Editor"],["Dawn"],["Dreamweaver"],["Eclipse"],["GitHub"],["Solarized Light"],["TextMate"],["Tomorrow"],["XCode"],["Kuroir"],["KatzenMilch"],["Ambiance","ambiance","dark"],["Chaos","chaos","dark"],["Clouds Midnight","clouds_midnight","dark"],["Cobalt","cobalt","dark"],["idle Fingers","idle_fingers","dark"],
["krTheme","kr_theme","dark"],["Merbivore","merbivore","dark"],["Merbivore Soft","merbivore_soft","dark"],["Mono Industrial","mono_industrial","dark"],["Monokai","monokai","dark"],["Pastel on dark","pastel_on_dark","dark"],["Solarized Dark","solarized_dark","dark"],["Terminal","terminal","dark"],["Tomorrow Night","tomorrow_night","dark"],["Tomorrow Night Blue","tomorrow_night_blue","dark"],["Tomorrow Night Bright","tomorrow_night_bright","dark"],["Tomorrow Night 80s","tomorrow_night_eighties","dark"],
["Twilight","twilight","dark"],["Vibrant Ink","vibrant_ink","dark"]]},setTheme:function(a){p(this.cookiePrefix+"_ace",a);var c=this;if(this.ctx&&this.ctx.getResourceManager())if(r[a])c.aceEditor.set("theme",a);else{var b=null,b=this.ctx.getResourceManager().getVariable(d.RESOURCE_VARIABLES.ACE);b||(b=this.ctx.getResourceManager().getVariable(d.RESOURCE_VARIABLES.APP_URL),b=!0===l("debug")?b+"/lib/ace/src-min-noconflict/":b+"/xfile/ext/ace/");b=b+"/theme-"+a+".js";this.loadScript(b,null,function(){r[a]=
!0;c.aceEditor.set("theme",a)})}else console.error("have no resource manager!!!")},_createThemeWidget:function(a,c){var b=this,d=new k({label:a,checked:!1,theme:c});dojo.connect(d,"onClick",function(){b.setTheme(c)});return d},_addThemes:function(a){for(var c=this.getThemeData(),b=this,d=function(a,c,d){return g.create(a,c,"View/Themes/"+a,!1,null,"TEXT","viewActions",null,!1,function(){b.setTheme(d)})},f=0;f<c.length;f++){var e=c[f],B=e[1]||e[0].replace(/ /g,"_").toLowerCase(),e=d(e[0],"",B);a.push(e)}},
setMode:function(a){if(this.ctx&&this.ctx.getResourceManager()){var c=this;if(!q[a]){var b=null,b=this.ctx.getResourceManager().getVariable(d.RESOURCE_VARIABLES.ACE);b||(b=this.ctx.getResourceManager().getVariable(d.RESOURCE_VARIABLES.APP_URL),b=!0===l("debug")?b+"/lib/ace/src-min-noconflict/":b+"/xfile/ext/ace/");b=b+"/mode-"+a+".js";this.loadScript(b,null,function(){q[a]=!0;c.aceEditor.set("mode",a)})}this.aceEditor.set("mode",a)}else console.error("have no resource manager!")},_addModes:function(a){for(var c=
this,b=[],d=0,f=0,f=0;f<t.length;f++)b.push("\x3cli\x3e\x3ca\x3e"+t[f]+"\x3c/a\x3e\x3c/li\x3e");for(var e='\x3ctable class\x3d"options-menu ui-widget-content"\x3e\x3ctr\x3e';;){for(var e=e+"\x3ctd\x3e\x3cul\x3e",f=15>b.length-d?b.length:d+15,g=b.slice(d,f),f=0;f<g.length;f++)e+=g[f];e+="\x3c/ul\x3e\x3c/td\x3e";d+=15;if(d>=b.length)break}e+="\x3c/tr\x3e\x3c/table\x3e";b=new k({label:"No Title"});a.menu.addChild(b);b.domNode.innerHTML=e;h.add(b.domNode,"options-menu");h.add(b.domNode,"ui-widget-content");
b.on("click",function(a){(a=a.target.text)&&c.setMode(a)})},getValue:function(){return this.aceEditor.get("value")},setValue:function(a){if(this.aceEditor)return this.aceEditor.set("value",a);console.error("ACEEditor::setValue failed, invalid state")},_getMode:function(a){a=a||this.fileName;var c="javascript";if(a){c=m.getFileExtension(a)||"js";if("js"===c||"xblox"===c)c="javascript";if("html"===c||"cfhtml"===c)c="html";"cp"===c&&(c="xml")}return c},startup:function(){if(!this.didStart){this.didStart=
!0;this.iconClassNormal=""+this.iconClass;this.set("iconClass","fa-spinner fa-spin");this.inherited(arguments);var a=this;this.value?this.attachACE(this.value):this.getContent(function(c){a.set("iconClass",a.iconClassNormal);a.lastSavedContent=c;a.attachACE(c)},function(c){a.attachACE()});this.on("click",function(){this.publish(d.EVENTS.ON_ITEM_SELECTED,{item:{},owner:this});if(a.onItemClear)a.onItemClear();if(a.onItemClick)a.onItemClick(null)})}}})});
//# sourceMappingURL=ACEEditor.js.map