//>>built
define("xide/views/ActionDialog","dojo/_base/declare dojo/dom-style dojo/on xide/views/Dialog xide/utils dojo/dom-attr xide/widgets/_InsertionMixin dojo/dom-geometry ./KeyboardHandlerLight xide/widgets/_CSSMixin dojo/dom-class dojo/window dojox/layout/ResizeHandle xide/factory xide/types".split(" "),function(k,g,l,m,n,h,p,e,q,r,f,t,u,v,w){return k("xide.views.ActionDialog",[m,p,q,r],{ctx:null,model:null,delegate:null,didLoad:!1,inserts:null,actionBar:null,autoDestroy:!0,autoActionButtons:!0,cssClass:"ui-state-default",
titleBarClass:null,focusedButton:"ok",autofocus:!1,dialogClass:"",duration:0,resizeable:!1,resizeToContent:!0,_didOk:!1,_size:function(){this._checkIfSingleChild();this._singleChild&&"undefined"!=typeof this._singleChildOriginalStyle&&(this._singleChild.domNode.style.cssText=this._singleChildOriginalStyle,delete this._singleChildOriginalStyle);var a=e.position(this.domNode),b=t.getBox(this.ownerDocument);b.w*=this.maxRatio;b.h*=this.maxRatio;if(a.w>=b.w||a.h>=b.h){var c=e.position(this.containerNode),
d=Math.min(a.w,b.w)-(a.w-c.w),a=Math.min(a.h,b.h)-(a.h-c.h);this._singleChild&&this._singleChild.resize?("undefined"==typeof this._singleChildOriginalStyle&&(this._singleChildOriginalStyle=this._singleChild.domNode.style.cssText),this._singleChild.resize({w:d,h:a})):g.set(this.containerNode,{width:d+"px",height:a+"px",overflow:"auto",position:"relative"})}else this._singleChild&&this._singleChild.resize&&this._singleChild.resize()},_resizeToContent:function(){var a=e.getContentBox(this.actionBar),
b=e.getMarginBox(this.containerNode),c=e.getMarginBox(this.titleBar);e.getMarginBox(this.domNode);g.set(this.domNode,{height:a.h+b.h+c.h+"px"})},hide:function(){var a=this,b=this.inherited(arguments);b.then(function(){a.autoDestroy&&setTimeout(function(){n.destroyWidget(a)},500)});return b},buildRendering:function(){this.inherited(arguments);f.add(this.domNode,this.dialogClass);f.add(this.domNode,"resizableDialog")},postMixInProperties:function(){this.inherited(arguments);var a=this.ctx;a&&a.getLocals&&
(this._messages=a.getLocals("dijit","common")||this._messages)},openItem:function(){return this.onOk()},onOk:function(){var a=this;if(this._didOk)this.hide();else return this._didOk=!0,this.hide().then(function(){if(a.delegate&&a.delegate.onOk)try{a.delegate.onOk(a)}catch(b){}})},onCancel:function(){var a=this;return this.hide().then(function(){if(a.delegate&&a.delegate.onCancel)a.delegate.onCancel(a)})},resize:function(a){if(a){h.set(this.domNode,"height","inherit");dojo.style(this.domNode,"height",
"inherit");h.set(this.domNode,"width","inherit");dojo.style(this.domNode,"width","inherit");dojo.style(this.domNode,"maxWidth","inherit");dojo.style(this.domNode,"maxHeight","inherit");var b=g.getComputedStyle(this.containerNode),b=e.getPadExtents(this.containerNode,b),c=a.w-b.w,d=a.h-b.h;d&&dojo.style(this.domNode,"height",d+"px");d-=e.getContentBox(this.titleBar).h;a=dojo.query(".dijitDialogPaneContent",this.domNode)[0];(b=this.actionBar)&&(d-=e.getMarginBox(b).h);c&&dojo.style(a,"width",c+"px");
c&&dojo.style(this.domNode,"width",c+"px");d&&dojo.style(a,"height",d+"px");dojo.forEach(this.getChildren(),dojo.hitch(this,function(a){a.resize&&a.resize({w:c,h:d})}));v.publish(w.EVENTS.RESIZE,{},this)}},addActionButtons:function(){if(!this.actionBar){this.translate("buttonOk",!1);var a=dojo.create("div",{className:"ui-widget-content",style:"bottom: 0;left: 0;position: absolute;width: 100%;margin:0px;padding:0px;text-align:right;"});this.actionBar=a;var b=this;this.domNode.appendChild(a);var c=
new dijit.form.Button({innerHTML:this.translate("buttonOk",!1),onClick:function(a){a.preventDefault();b.onOk()}});this.okButton=c;a.appendChild(c.domNode);c.startup();c=new dijit.form.Button({innerHTML:this.translate("buttonCancel",!1),style:!0===this.resizeable?"margin-right:15px":"",onClick:function(){b.onCancel();b.hide();b.destroyRecursive()}});a.appendChild(c.domNode);c.startup();this.cancelButton=c;f.add(this.okButton.domNode,"ui-button ui-widget-content");f.add(this.cancelButton.domNode,"ui-button ui-widget-content");
this.resizeable&&(c=dojo.doc.createElement("div"),a.appendChild(c),new u({targetId:this.id},c));f.add(this.containerNode,"ui-widget-content")}},fixHeight:function(){var a=e.getMarginBox(this.actionBar),a=e.getMarginBox(this.domNode).h+a.h;g.set(this.domNode,{height:a+"px"});var b=this;g.set(b.containerNode,{height:"inherit"});b._position();setTimeout(function(){setTimeout(function(){b._position()},10)},1E3)},show:function(){var a=this;return this.inherited(arguments).then(function(){a.resizeToContent&&
a._resizeToContent();setTimeout(function(){if("ok"===a.focusedButton&&a.okButton)try{a.okButton.focus(),a.okButton.domNode.focus()}catch(b){console.error("focus error!")}},300)})},startup:function(){this.inherited(arguments);if(!this.didLoad){this.didLoad=!0;f.add(this.titleBar,"ui-widget-content");var a=this;this.inserts&&this.doInserts(this.inserts);l(this.domNode,"keydown",function(b){a.onKey(b)});this.autoActionButtons&&this.addActionButtons();this.titleBarClass&&f.add(this.titleBar,this.titleBarClass);
this.focusedButton&&this.okButton&&setTimeout(function(){a.okButton.domNode.focus()},500);this.resize()}}})});
//# sourceMappingURL=ActionDialog.js.map