//>>built
define("xide/views/ExternalEditor",["dojo/_base/declare","xide/widgets/TemplatedWidgetBase","xide/utils"],function(c,d,e){return c("xide.views.ScriptEditor",[d],{wFloatingPane:null,didStartup:!1,title:"Scripts",idName:"scriptGroup",labelUserFolder:"User",labelSystemFolder:"System",labelAppFolder:"App",labelScope:"Scope",appFolderRadio:null,systemFolderRadio:null,userFolderRadio:null,toolBarMenu:null,currentScope:"XAPP",currentScopePath:null,scriptFrame:null,scriptRoot:null,frameUrl:null,wNewCustomApp:null,
wNewPlugin:null,scriptFrameParent:null,toolBarHeight:"27px",wReloadButton:null,editorWaitingTime:4E3,menuBar:null,editorUrl:null,isLoading:!1,templateString:"\x3cdiv id\x3d'scriptContentPane' class\x3d'scriptEditor' data-dojo-type\x3d'dojox.layout.ContentPane' title\x3d'${!title}' data-dojo-attach-point\x3d'wFloatingPane' style\x3d''\x3e\x3cdiv id\x3d'scriptFrameParent' class\x3d'scriptFrameParent' data-dojo-attach-point\x3d'scriptFrameParent'\x3e\x3c/div\x3e\x3c/div\x3e",onEditorReady:function(a){var b=
dijit.registry.byId("scriptStandBy");b&&b.hide();this.frameUrl=a;if(!a)return null;this._focusEditor();this.isLoading=!1;this.scriptFrame=new easyXDM.Socket({remote:a,container:this.scriptFrameParent,props:{style:{width:"100%",height:"100%"},width:"100%",height:"100%"},onload:function(){console.error("iframe ready")},onReady:function(){console.error("xdm ready")},onMessage:function(a,b){}});console.error("scriptFrame : "+this.scriptFrame.id)},_focusEditor:function(){setTimeout(function(){var a=dojo.query('[id*\x3d"easyXDM_"]');
if(null!=a&&0<a.length)for(var b=0;b<a.length;b++)a[b].contentWindow&&a[b].contentWindow.focus()},200)},createScriptFrame:function(a){if(!this.isLoading){this.isLoading=!0;var b=this;sctx.getScriptManager().serviceObject.getScriptIFrameUrl(sctx.getSession().getUUID(),sctx.getSession().getAppId(),sctx.getSession().getStylePlatform(),a).addCallback(function(a){setTimeout(function(){b.onEditorReady(a)},b.editorWaitingTime)})}},onShowEditor:function(){this._focusEditor();var a=sctx.getSession().getCXAppRoot();
if(!this.scriptFrame&&"XAPP"==this.currentScope){var b=dijit.registry.byId("scriptStandBy");b&&b.show();this.currentScopePath=this.getCurrentScope();this.createScriptFrame(this.getCurrentScope())}a&&this.wNewCustomApp&&(e.destroyWidget(this.wNewCustomApp),this.wNewCustomApp=null);console.error("on show editor")},onHide:function(){},destroy:function(){},buildRendering:function(){this.inherited(arguments)},onCustomAppReady:function(a){location.reload()},onNewCustomAppOk:function(a){var b=this;sctx.getScriptManager().serviceObject.createCustomApp(sctx.getSession().getUUID(),
sctx.getSession().getAppId(),sctx.getSession().getStylePlatform(),a.customAppSettingsView.folderType).addCallback(function(a){setTimeout(function(){b.onCustomAppReady(a)},100)})},openCustomAppWizard:function(){var a=this;xas.factory.createNewCustomAppDialog({onOk:function(b){a.onNewCustomAppOk(b)}},sctx.getSession().getUUID(),sctx.getSession().getAppId(),sctx.getSession().getStylePlatform())},getCurrentScope:function(){return this.appFolderRadio.get("checked")?"%XAPP%":this.userFolderRadio.get("checked")?
"%XUSER%":this.systemFolderRadio.get("checked")?"%XAPP%":null},onNewCustomPluginOk:function(a){var b=this.getCurrentScope();sctx.getScriptManager().serviceObject.createCustomPlugin(sctx.getSession().getUUID(),sctx.getSession().getAppId(),a.settingsView.wIdentifier.get("value"),b).addCallback(function(a){setTimeout(function(){location.reload()},100)})},openCustomPluginWizard:function(){var a=this;xas.factory.createNewCustomPluginDialog({onOk:function(b){a.onNewCustomPluginOk(b)}},sctx.getSession().getUUID(),
sctx.getSession().getAppId(),sctx.getSession().getStylePlatform())},onNewCustomApp:function(){sctx.getSession().getCXAppRoot()||this.openCustomAppWizard()},reloadScriptEditor:function(a){var b=dijit.registry.byId("scriptStandBy");b&&b.show();dojo.empty(this.scriptFrameParent);this.scriptFrame=null;this.currentScopePath=a||this.getCurrentScope();this.createScriptFrame(a||this.currentScopePath)},changeScope:function(a){},_registerMenuHandlers:function(){var a=this;this.wNewCustomApp&&dojo.connect(this.wNewCustomApp,
"onClick",function(b){a.onNewCustomApp()});this.wNewPlugin&&dojo.connect(this.wNewPlugin,"onClick",function(b){a.openCustomPluginWizard()});dojo.connect(this.wReloadButton,"onClick",function(b){setTimeout(function(){a.reloadScriptEditor()},800)});this.connect(this.appFolderRadio,"onClick",function(b){setTimeout(function(){a.reloadScriptEditor()},800)});this.connect(this.userFolderRadio,"onClick",function(b){setTimeout(function(){a.reloadScriptEditor()},800)});this.connect(this.systemFolderRadio,"onClick",
function(b){setTimeout(function(){a.reloadScriptEditor()},800)})},startup:function(){this.didStartup||(this.inherited(arguments),this.didStartup=!0,this._registerMenuHandlers(),"undefined"!=typeof isAdmin&&!0===isAdmin&&this.systemFolderRadio.set("disabled",!1))}})});
//# sourceMappingURL=ExternalEditor.js.map