//>>built
define("xide/views/GridView","dojo/_base/declare dojo/dom-class xide/types xide/factory xide/utils dgrid/Selection xide/grid/_GridKeyboardSelection xide/grid/_GridKeyNavMixin xide/grid/_GridKeyboardHandler".split(" "),function(h,g,f,k,d,l,m,n,p){return h("xide/views/GridView",[p],{grid:null,childSelector:".dgrid-row",itemType:0,handleContainerClick:!0,resizeHeightToParent:!0,clearSelection:!1,selectedItemNode:null,selectedItem:null,selectedItems:null,keyboardNavigation:!1,mouseNavigation:!1,openTreeOnEnter:!1,
dnd:!0,gridParams:null,autoHeight:!1,autoSelectOnShow:!0,beanType:null,parentField:"parentId",onShow:function(){this.onContainerFocus()},select:function(a,b){this.grid.select(a);!0===b&&this.focusItem(a)},expand:function(a,b){this._isExpanded(a)||this.grid.expand(a);!0===b&&this.focusItem(a)},_isExpanded:function(a){if(a=this.toFocusNode(a)){var b=d.find(".ui-icon-triangle-1-se",a,!0);if(b)return!0;b=d.find(".ui-icon-triangle-1-e",a,!0);if(!b)return null}return!1},addGridBases:function(a){debugger;
this.keyboardNavigation&&a.push(Keyboard);return a},onRight:function(a){(a=this.grid.row(a))&&this.grid.expand&&this.grid.expand(a)},onLeft:function(a){if((a=this.grid.row(a))&&a.data&&a.data[this.parentField]){var b=a.data;if(!this._isExpanded(a.data)){var c=this.store.getSync(b[this.parentField]);if(c){this.select(c,!0);return}if(this.blockScope&&(c=this.blockScope.getBlockById(b.parentId))){this.select(c,!0);return}}}a&&this.grid.expand&&this.grid.expand(a)},onEnter:function(a){if(this.delegate&&
this.delegate.onGridKeyEnter)this.delegate.onGridKeyEnter(a)},focusNode:function(a){this.focusChild(a)},toFocusNode:function(a){if((a=this.grid.row(a))&&a.element){var b=d.find(".dgrid-cell",a.element,!0);return b?b:a.element}return(b=d.find(".dgrid-row",this.grid.domNode,!0))?b:null},focusItem:function(a,b){if(b)this.nextFocusItem=a;else if(this.grid.row(a)){var c=this.toFocusNode(a);!c&&this.focusedChildNode&&(c=this.focusedChildNode);c?(this.grid._focusNode=c,this.grid.focus&&this.grid.focus(c),
c.focus()):console.error("have no focus node")}else console.error("have no focus row")},getCurrentItemNodes:function(a){return(a=d.find(".dgrid-row",a||this.domNode,!1))?a:null},getNumberOfItems:function(a){return(a=d.find(".dgrid-row",a||this.domNode,!1))?a.length:0},_onGridDataChanged:function(a){var b=a.cell,c=null;b&&b.row&&b.row.data&&(c=b.row.data);a={item:c,id:a.rowId,oldValue:a.oldValue,newValue:a.value,grid:this.grid,field:b.column.field};if(this.delegate&&this.delegate.onGridDataChanged)this.delegate.onGridDataChanged(a)},
_onGridEditorShow:function(a){if(this.delegate&&this.delegate.onGridEditorShow)this.delegate.onGridEditorShow(a)},onGridCreated:function(a){a=a||this.grid;var b=this;this.autoHeight&&g.add(this.grid.domNode,"dgrid-autoheight");if(this.handleContainerClick)a.on("click",function(a){if(a&&a.target&&g.contains(a.target,"dgrid-content"))b.onContainerFocus()});a.on("dgrid-select",function(a){if(!b.isForcedFocus)if(a&&a.rows&&1==a.rows.length){b.prevItem=a.rows[0].data;b.prevFocusNode=a.rows[0].element;
if(b.ctlrKeyDown)b.onItemSelected(a.rows);else b.onItemSelected(a.rows[0].data,a.rows[0].element);b.lastSelectedRowItem=a.rows[0].data}else if(a&&a.rows&&1<=a.rows.length)b.onItemsSelected(a.rows)});a.on("dgrid-datachange",function(a){b._onGridDataChanged(a)});a.on("dgrid-error",function(a){});a.on("dgrid-editor-show",function(a){b._onGridEditorShow(a)});if(this.mouseNavigation)a.on("dblclick",function(a){b.onMouseDoubleClickEvent(a)});a.on("keydown",function(a){b.onKey(a)});a.on("keyup",function(a){b.onKeyUp(a)})},
restoreFocus:function(){this.onContainerFocus()},onContainerFocus:function(){var a=this;if(this.delegate.onItemSelected)this.delegate.onItemSelected(null);this.clearSelection?(this.grid.clearSelection(),this.selectedItems=this.selectedItem=null,this.selectedItemNode&&this.selectedItemNode.blur(),this.selectedItemNode=null):setTimeout(function(){a.onFocusRootNode()},1)},_getValidItem:function(a){for(var b=0;b<a.length;b++){var c=this.grid.row(a[b]);if(c&&c.data&&"."!==c.data.name)return c.data}return null},
getFirstItem:function(){var a=d.find(".dgrid-row",this.grid.domNode,!1);return a&&0<a.length&&(a=this._getValidItem(a))?a:null},focusFirstItem:function(){if(this._getFirst){var a=this._getFirst();a?(this.focusItem(a,!1),this.grid._focusNode=a,this.grid.focus(a)):console.error("focusFirstItem:failed")}},onFocusRootNode:function(){this.prevFocusNode?(this.isForcedFocus=!0,this.focusItem(this.prevFocusNode,!1),this.grid._focusNode=this.prevFocusNode,this.grid.focus&&this.grid.focus(this.prevFocusNode),
this.isForcedFocus=!1):this.focusFirstItem()},onKeyboardSearch:function(a,b,c,e){a&&a.data&&this.focusItem(a.data,!1)},onGridRefreshed:function(){null!=this.activeItem&&this._restoreItem(this.activeItem);try{this.nextFocusItemForce?(this.focusItem(this.nextFocusItemForce,!1),this.nextFocusItemForce=null):this.autoFocus&&this.nextFocusItem&&this.focusItem(this.nextFocusItem,!1)}catch(a){console.error("onGridFreshed::focus : went wrong!")}setTimeout(function(){k.publish(f.EVENTS.RESIZE,{},this)},100);
this.grid.resize()},onSelected:function(a){a=this.grid.getItem(a);a.directory&&this.delegate.updateGrid(a)},onItemChanged:function(a,b){this.grid.refresh()},getActiveItem:function(){return this.activeItem},onKeyEvent:function(a){if(this.keyboardDelegate)this.keyboardDelegate.onGridKey(a)},onMouseEvent:function(a){if(this.mouseDelegate)this.mouseDelegate.onGridMouse(a)},onMouseDoubleClickEvent:function(a){if(this.delegate&&this.delegate.onGridMouseDoubleClick)this.delegate.onGridMouseDoubleClick(a)},
getCurrentSelection:function(a){if(!0===a){a=[];var b=d.find(".dgrid-selected",this.grid.domNode,!1);if(null==b||0==b.length)return null;for(var c=0;c<b.length;c++){var e=this.grid.row(b[c]);null!=e&&null!=e.data&&null!=e.data.name&&"."!=e.data.name&&".."!=e.data.name&&a.push(e.data)}return 0<a.length?a:null}return this.selectedItems},onItemsSelected:function(a,b){this.selectedItems=[];for(var c=0;c<a.length;c++){var e=a[c],d=e.data;e&&d&&".."!=e.data&&this.selectedItems.push(d)}},onItemSelected:function(a,
b){this.selectedItem=a;this.selectedItemNode=b;this.selectedItems=[a];var c={store:this.store,item:a,owner:this,type:this.itemType,view:this};this.beanType&&(c.beanType=this.beanType);try{this.publish(f.EVENTS.ON_ITEM_SELECTED,c)}catch(e){console.error("publish ON_ITEM_SELECTED failed "+e)}if(c=d.find(".dgrid-cell",b,!0))this.focusedChildNode=c,this.focusedChildNode.data=a;this.activeItem=a;if(this.delegate.onItemSelected)this.delegate.onItemSelected(a);b&&b.focus&&b.focus()},refresh:function(a){a?
(this.store=a,this.grid.set("collection",a)):this.grid.refresh()},onResize:function(){this.resizeHeightToParent&&this.domNode&&this.domNode.parentNode&&d.mimicNode(this.domNode,this.domNode.parentNode,!1,!0);this.domNode&&this.grid&&this.grid.resize()},startup:function(){try{this.inherited(arguments),this.subscribe(f.EVENTS.RESIZE,this.onResize)}catch(a){console.error("grid view startup crash : "+a)}},getGridBaseClasses:function(a,b){b.keyboardNavigation&&a.push(m);b.keyboardSelect&&a.push(n);b.selection&&
a.push(l);return a}})});
//# sourceMappingURL=GridView.js.map