//>>built
define("xide/views/ToggleSplitter",["dojo","dijit","xide/factory","xide/types"],function(d,h,k,l){var m=d.declare("xide.views.ToggleSplitter",h.layout._Splitter,{container:null,child:null,region:null,state:"full",_closedSize:"0",delegate:null,baseClass:"dojoxToggleSplitter",templateString:'\x3cdiv class\x3d"dijitSplitter dojoxToggleSplitter" dojoAttachEvent\x3d"onkeypress:_onKeyPress,onmousedown:_startDrag,onmouseenter:_onMouse,onmouseleave:_onMouse"\x3e\x3cdiv dojoAttachPoint\x3d"toggleNode" class\x3d"dijitSplitterThumb dojoxToggleSplitterIcon" tabIndex\x3d"0" role\x3d"separator" dojoAttachEvent\x3d"onmousedown:_onToggleNodeMouseDown,onclick:_toggle,onmouseenter:_onToggleNodeMouseMove,onmouseleave:_onToggleNodeMouseMove,onfocus:_onToggleNodeMouseMove,onblur:_onToggleNodeMouseMove"\x3e\x3cspan class\x3d"dojoxToggleSplitterA11y" dojoAttachPoint\x3d"a11yText"\x3e\x3c/span\x3e\x3c/div\x3e\x3c/div\x3e',
postMixInProperties:function(){this.inherited(arguments);this.container&&this.container.cookieName&&(this._cookieName=this.container.cookieName+"_"+this.region)},postCreate:function(){this.inherited(arguments);var a=this.region;d.addClass(this.domNode,this.baseClass+a.charAt(0).toUpperCase()+a.substring(1))},startup:function(){this.inherited(arguments);var a=this.child.domNode,b=d.style(a,this.horizontal?"height":"width");this.domNode.setAttribute("aria-controls",a.id);d.forEach(["toggleSplitterState",
"toggleSplitterFullSize","toggleSplitterCollapsedSize"],function(a){var b=a.substring(14),b=b.charAt(0).toLowerCase()+b.substring(1);a in this.child&&(this[b]=this.child[a])},this);this.fullSize||(this.fullSize="full"==this.state?b+"px":"75px");this._openStyleProps=this._getStyleProps(a,"full");this._started=!0;this.set("state",this.state);return this},_onKeyPress:function(a){"full"==this.state&&this.inherited(arguments);a.charCode!=d.keys.SPACE&&a.keyCode!=d.keys.ENTER||this._toggle(a)},_onToggleNodeMouseDown:function(a){d.stopEvent(a);
this.toggleNode.focus()},_startDrag:function(a){"full"==this.state&&this.inherited(arguments)},_stopDrag:function(a){this.inherited(arguments);this.toggleNode.blur();this.container&&!1!==this.container.publishResizeOnToggleMove&&k.publish(l.EVENTS.RESIZE,{},this);if(this.delegate&&this.delegate.onToggleSplitterSplitterMove)this.delegate.onToggleSplitterSplitterMove(this)},_toggleEx:function(a,b){switch(this.state){case "full":b=this.collapsedSize?"collapsed":"closed";break;case "collapsed":b="closed";
break;default:b="full"}this.set("state",b);var c=this;setTimeout(function(){if(c.delegate&&c.delegate.onChangeToggleSplitterState)c.delegate.onChangeToggleSplitterState(c,b)},100)},_toggle:function(a){try{this._toggleEx(a)}catch(b){}var c=this;setTimeout(function(){k.publish(l.EVENTS.RESIZE,{},c)},500)},_onToggleNodeMouseMove:function(a){var b=this.baseClass,c=this.toggleNode,f="full"==this.state||"collapsed"==this.state;a="mouseout"==a.type||"blur"==a.type;d.toggleClass(c,b+"IconOpen",a&&f);d.toggleClass(c,
b+"IconOpenHover",!a&&f);d.toggleClass(c,b+"IconClosed",a&&!f);d.toggleClass(c,b+"IconClosedHover",!a&&!f)},_handleOnChange:function(a){a=this.child.domNode;var b,c,f=this.horizontal?"height":"width";"full"==this.state?(c=d.mixin({display:"block",overflow:"auto",visibility:"visible"},this._openStyleProps),c[f]=this._openStyleProps&&this._openStyleProps[f]?this._openStyleProps[f]:this.fullSize,d.style(this.domNode,"cursor",""),d.style(a,c)):"collapsed"==this.state?(c=d.getComputedStyle(a),this._openStyleProps=
b=this._getStyleProps(a,"full",c),d.style(this.domNode,"cursor","auto"),d.style(a,f,this.collapsedSize)):(this.collapsedSize||(c=d.getComputedStyle(a),this._openStyleProps=b=this._getStyleProps(a,"full",c)),c=this._getStyleProps(a,"closed",c),d.style(this.domNode,"cursor","auto"),d.style(a,c));this._setStateClass();this.container._started&&this.container._layoutChildren(this.region)},_getStyleProps:function(a,b,c){c||(c=d.getComputedStyle(a));var f={},e=this.horizontal?"height":"width";f.overflow=
"closed"!=b?c.overflow:"hidden";f.visibility="closed"!=b?c.visibility:"hidden";f[e]="closed"!=b?a.style[e]||c[e]:this._closedSize;var g=["Top","Right","Bottom","Left"];d.forEach(["padding","margin","border"],function(a){for(var d=0;d<g.length;d++){var e=a+g[d];"border"==a&&(e+="Width");void 0!==c[e]&&(f[e]="closed"!=b?c[e]:0)}});return f},_setStateClass:function(){var a="\x26#9652",b=this.region.toLowerCase(),c=this.baseClass,f=this.toggleNode,e="full"==this.state||"collapsed"==this.state,g=this.focused;
d.toggleClass(f,c+"IconOpen",e&&!g);d.toggleClass(f,c+"IconClosed",!e&&!g);d.toggleClass(f,c+"IconOpenHover",e&&g);d.toggleClass(f,c+"IconClosedHover",!e&&g);if("top"==b&&e||"bottom"==b&&!e)a="\x26#9650";else if("top"==b&&!e||"bottom"==b&&e)a="\x26#9660";else if("right"==b&&e||"left"==b&&!e)a="\x26#9654";else if("right"==b&&!e||"left"==b&&e)a="\x26#9664";this.a11yText.innerHTML=a},_setStateAttr:function(a){if(this._started){var b=this.state;this.state=a;this._handleOnChange(b);switch(a){case "full":this.domNode.setAttribute("aria-expanded",
!0);a="onOpen";break;case "collapsed":this.domNode.setAttribute("aria-expanded",!0);a="onCollapsed";break;default:this.domNode.setAttribute("aria-expanded",!1),a="onClosed"}this[a](this.child)}},onOpen:function(a){},onCollapsed:function(a){},onClosed:function(a){}});d.extend(h._Widget,{toggleSplitterState:"full",toggleSplitterFullSize:"",toggleSplitterCollapsedSize:""});return m});
//# sourceMappingURL=ToggleSplitter.js.map